<a href="https://colab.research.google.com/github/mati1yas/Machine-Learning-Track/blob/main/checkPoints_Answers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [ ]:
import itertools as it
import numpy as np

arr=np.array(['A','B','C'])
combs= list(it.combinations(arr,2))
combs

[('A', 'B'), ('A', 'C'), ('B', 'C')]

**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [ ]:
import itertools as it

datacycle=it.cycle( ['Python', 'is', 'fun'] )     # create infinite cycle of the given list of data

for _ in range(10):      # do the operation ten times
  word= next(datacycle)   # we are using next to get next element

  print(word)





Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [ ]:
import glob as gb

python_files = gb.glob('*.py')  # this will return me list of all the files with .py file extension
print(python_files)

['python1.py', 'python2.py', 'python4.py', 'python3.py']


**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [ ]:
#<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>

In [1]:
from bs4 import BeautifulSoup           # import beautifulsoup library
html="<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"

def extractText(html):
  soup= BeautifulSoup(html,'html.parser')  # create soup object

  pTag =  soup.find('p')    # since we have only one p tag we can use find
  text =  pTag.text       # extract text we can also use get_text()
  return text

text= extractText(html)

text

'AI is transforming the world'

**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [7]:
# Occurrence Replacement we can use two approaches

import re                   # import re module
html="<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"

def substitute(html):
  html1=re.sub("AI","Aritificial Intelligence",html)          # use sub method of re module
  return html1
print(substitute(html))

# we can also use string replacement

def replace(html):
  html2 = html.replace("AI","Artificial Intelligence")      # using string replacement
  return html2

html2=replace(html)

html2

#  result of both above operation is the similar






<html><body><div class='main'><h1>Welcome to Aritificial Intelligence</h1><p>Aritificial Intelligence is transforming the world</p></div></body></html>


"<html><body><div class='main'><h1>Welcome to Artificial Intelligence</h1><p>Artificial Intelligence is transforming the world</p></div></body></html>"

**CP6**: Create a numpy array of 10 zeros.

In [ ]:
import numpy as np    # import numpy library

arr= np.zeros(10)     # create array of size 10 with all elements as zero
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**CP7** Create a numpy array of the integers from 10 to 49.

In [ ]:
arr=np.arange(10,50)     # create array of range between 10 - 49
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [ ]:
arr= np.arange(9)      # create array of size 9
print(arr)
tripled_array= arr.reshape(3,3)  # reshape the array to 3*3
print(tripled_array)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

some of the reasons why Machine Learning Model need large dataset :
  1. **For Better Learning or Model Generalisation**: when models have large example to learn from , they become better at understanding patterns and variation in the data
  2. **to Avoid overfitting**: sometimes models can become too focused on a data they are trained on which leads to poor performance when face new data . having large dataset will makes the machine learning models learn new pattern and variation than memorize a pattern.
  3. **Nature of Problem**:  some problems need large dataset inorder for them to point out pattern or variation in the data. **Language processing** and **Image Processing** can be mentioned as an example .

what does it mean for an amount of data to be **large**?

I could not get exact definition that qualiefies a data as large or small .  we can atleast say it is data that is larger in size than a data size that is usually used in Machine learning . the main question to answer here is, do we have a data that is diverse enough and representative to train the model so that it can make accurate predictions and decisions.

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

while reading i came across many adversial ways of using AI . some of them were more interesting than the others . I found the below as interesting :
1. **Deepfake and synthetic Media**: is technique of using artificial intelligence to create highly realistic fake images, videos, or audio that appear to be authentic.

2. **Fooling captcha system**: as we all know the main intention of captcha was to identify between robot and humans .  however methods to bypass captcha using computer vision algorithms .

some of Prevention methods could be as follows .

1. **Regulations and Standards**: Establishing regulations and standards for AI systems can play a significant role in preventing adversarial use.
2. **Data Security and Privacy**: Protecting data from manipulation and unauthorized access is also other option we have for adversial use of AI prevention .